# brodcasting







In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
l1 = [0,1,2,3,4,5,6,7,8,9]

In [5]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
l1[1]/10

0.1

In [7]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [9]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
arr[arr>5]

array([6, 7, 8, 9])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1=arr[0:6]

In [13]:
arr1

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [16]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1[:]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr1[:]=555

In [19]:
arr1

array([555, 555, 555, 555, 555, 555])

In [20]:
arr1

array([555, 555, 555, 555, 555, 555])

In [21]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [22]:
arr1

array([555, 555, 555, 555, 555, 555])

In [23]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# copy of an array


In [24]:
arr2 =arr.copy()

In [25]:
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [26]:
arr2[:]=1000

In [27]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [28]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# python list vs numpy array

In [29]:
size =1000
x= range(size)
y= range(size)

In [30]:
%%timeit
[x[i]*y[i] for i in range(size)]

216 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
x1=np.arange(size)
y1=np.arange(size)

In [34]:
%%timeit
x1*y1

1.26 µs ± 25.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# insert

In [35]:
b= np.array([[1,2,3],[4,5,6,],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b1= np.insert(b,1,[15,16,17],axis=0)

In [38]:
 np.insert(b,1,[15,16,17],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [39]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# matrix


In [45]:
x = np.matrix('1,2,3;4,5,6;7,8,9')

In [47]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
x[2,1] =-7

In [50]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [51]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr[2:1]=-7

In [54]:
np.insert(arr,2,2)

array([1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x*x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [56]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
arr@arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# storage in file

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.savetxt('a.txt',arr)

In [60]:
np.savetxt('a.txt',arr,delimiter=',')

In [61]:
np.loadtxt('a.txt',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [62]:
np.save('data.npy',arr)

In [63]:
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a= np.arange(10)

In [65]:
np.savez('both.npz',arr,a)

In [66]:
z=np.load('both.npz')

In [67]:
z.files

['arr_0', 'arr_1']

In [69]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
import pandas as pd 
import  numpy as np

# using list

In [71]:
my_list= [100,200,300,400,500]

In [75]:
x= pd.Series(my_list,index=['A','B','C','D','E'])

In [77]:
x

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [78]:
type(x)

pandas.core.series.Series

### using numpy array

In [79]:
arr = np.array(my_list)

In [80]:
arr

array([100, 200, 300, 400, 500])

In [81]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [83]:
pd.Series(arr,'A B C D E '.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

### USING DICTIONARIES

In [84]:
dict1={'A':100,'B':200,'C':300}

In [87]:
z1=pd.Series(dict1)
z1

A    100
B    200
C    300
dtype: int64

In [90]:
z2=pd.Series([10,20,30,40],'A B C D'.split())

In [91]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [92]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

### slicing in series

### z2

In [93]:
z2[0:2]

A    10
B    20
dtype: int64

In [94]:
z2['A':'C']

A    10
B    20
C    30
dtype: int64

# .LOC& .ILOC FUNCTIONS

In [95]:
z2.loc['A':'c']

A    10
B    20
C    30
D    40
dtype: int64

In [96]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [100]:
z=pd.Series({100:'a',200:'b',300:'c'})
z

100    a
200    b
300    c
dtype: object

In [102]:
z.iloc[0]

'a'

# operations

In [103]:
z1

A    100
B    200
C    300
dtype: int64

In [104]:
z1>100

A    False
B     True
C     True
dtype: bool

In [105]:
z1>200

A    False
B    False
C     True
dtype: bool

# broadcasting

In [106]:
z1+300

A    400
B    500
C    600
dtype: int64

# ordering

In [107]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [109]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [110]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [111]:
z2.sort_values(ascending=False,inplace=True)

In [112]:
z2

D    40
C    30
B    20
A    10
dtype: int64

# aggregation on series

In [113]:
z2

D    40
C    30
B    20
A    10
dtype: int64

In [114]:
z2.min()

10

In [115]:
z2.max()

40

In [116]:
z2.idxmax()

'D'

# data frame

In [119]:
rand_mat=np.random.randn(5,4)

In [120]:
rand_mat

array([[-0.31697898,  1.39711304, -1.35039856, -2.00309278],
       [-0.44595887,  1.33146373, -0.30764766,  0.21230819],
       [ 0.28333534,  1.04562976, -0.98564848,  0.25736519],
       [-0.09316582,  1.69237726,  0.46460956, -0.9405352 ],
       [ 1.46743671, -0.34901805, -0.25658427,  0.45771574]])

In [121]:
df=pd.DataFrame(data=rand_mat, index='A B C D E'.split(),columns='W X Y Z'.split())

In [122]:
df

W         X         Y         Z
A -0.316979  1.397113 -1.350399 -2.003093
B -0.445959  1.331464 -0.307648  0.212308
C  0.283335  1.045630 -0.985648  0.257365
D -0.093166  1.692377  0.464610 -0.940535
E  1.467437 -0.349018 -0.256584  0.457716

In [123]:
type(df)

pandas.core.frame.DataFrame

df['W']

In [126]:
type(df['W'])

pandas.core.series.Series

# SELECTION & INDEXING

In [127]:
df.loc['A']

W   -0.316979
X    1.397113
Y   -1.350399
Z   -2.003093
Name: A, dtype: float64

In [129]:
type(df['W'])

pandas.core.series.Series

# add a new column

In [131]:
df['New']=df['W']+ df['Y']

In [132]:
df

W         X         Y         Z       New
A -0.316979  1.397113 -1.350399 -2.003093 -1.667378
B -0.445959  1.331464 -0.307648  0.212308 -0.753607
C  0.283335  1.045630 -0.985648  0.257365 -0.702313
D -0.093166  1.692377  0.464610 -0.940535  0.371444
E  1.467437 -0.349018 -0.256584  0.457716  1.210852

In [134]:
df.drop('New',axis=1)

W         X         Y         Z
A -0.316979  1.397113 -1.350399 -2.003093
B -0.445959  1.331464 -0.307648  0.212308
C  0.283335  1.045630 -0.985648  0.257365
D -0.093166  1.692377  0.464610 -0.940535
E  1.467437 -0.349018 -0.256584  0.457716

In [135]:
df

W         X         Y         Z       New
A -0.316979  1.397113 -1.350399 -2.003093 -1.667378
B -0.445959  1.331464 -0.307648  0.212308 -0.753607
C  0.283335  1.045630 -0.985648  0.257365 -0.702313
D -0.093166  1.692377  0.464610 -0.940535  0.371444
E  1.467437 -0.349018 -0.256584  0.457716  1.210852

In [137]:
df.drop('New',axis=1,inplace=True)

In [138]:
df

W         X         Y         Z
A -0.316979  1.397113 -1.350399 -2.003093
B -0.445959  1.331464 -0.307648  0.212308
C  0.283335  1.045630 -0.985648  0.257365
D -0.093166  1.692377  0.464610 -0.940535
E  1.467437 -0.349018 -0.256584  0.457716

# add a new row

In [139]:
df.loc['F']= df.loc['A']+df.loc['C']

In [140]:
df

W         X         Y         Z
A -0.316979  1.397113 -1.350399 -2.003093
B -0.445959  1.331464 -0.307648  0.212308
C  0.283335  1.045630 -0.985648  0.257365
D -0.093166  1.692377  0.464610 -0.940535
E  1.467437 -0.349018 -0.256584  0.457716
F -0.033644  2.442743 -2.336047 -1.745728

In [141]:
df.drop('F',axis=0,inplace=True)

In [142]:
df

W         X         Y         Z
A -0.316979  1.397113 -1.350399 -2.003093
B -0.445959  1.331464 -0.307648  0.212308
C  0.283335  1.045630 -0.985648  0.257365
D -0.093166  1.692377  0.464610 -0.940535
E  1.467437 -0.349018 -0.256584  0.457716

In [143]:
df['X']['C']

1.0456297558559944

In [151]:
df.loc['C']['X']

1.0456297558559944

# DATA INPUT & OUTPUT

In [153]:
pd.read_csv('electronic-card-transactions-march-2024-csv-tables.csv')

Series_reference   Period  Data_value Suppressed STATUS    UNITS  \
0           ECTA.S19A1  2001.03      2462.5        NaN      F  Dollars   
1           ECTA.S19A1  2002.03     17177.2        NaN      F  Dollars   
2           ECTA.S19A1  2003.03     22530.5        NaN      F  Dollars   
3           ECTA.S19A1  2004.03     28005.1        NaN      F  Dollars   
4           ECTA.S19A1  2005.03     30629.6        NaN      F  Dollars   
...                ...      ...         ...        ...    ...      ...   
20356       ECTQ.S4AXP  2023.03        31.9        NaN      F  Percent   
20357       ECTQ.S4AXP  2023.06        33.0        NaN      F  Percent   
20358       ECTQ.S4AXP  2023.09        33.2        NaN      F  Percent   
20359       ECTQ.S4AXP  2023.12        32.7        NaN      F  Percent   
20360       ECTQ.S4AXP  2024.03        32.0        NaN      F  Percent   

       Magnitude                                        Subject  \
0              6  Electronic Card Transactions (ANZSIC06) - ECT   
1              6  Electronic Card Transactions (ANZSIC06) - ECT   
2              6  Electronic Card Transactions (ANZSIC06) - ECT   
3              6  Electronic Card Transactions (ANZSIC06) - ECT   
4              6  Electronic Card Transactions (ANZSIC06) - ECT   
...          ...                                            ...   
20356          0  Electronic Card Transactions (ANZSIC06) - ECT   
20357          0  Electronic Card Transactions (ANZSIC06) - ECT   
20358          0  Electronic Card Transactions (ANZSIC06) - ECT   
20359          0  Electronic Card Transactions (ANZSIC06) - ECT   
20360          0  Electronic Card Transactions (ANZSIC06) - ECT   

                                                   Group Series_title_1  \
0      Total values - Electronic card transactions A/...         Actual   
1      Total values - Electronic card transactions A/...         Actual   
2      Total values - Electronic card transactions A/...         Actual   
3      Total values - Electronic card transactions A/...         Actual   
4      Total values - Electronic card transactions A/...         Actual   
...                                                  ...            ...   
20356  Electronic card transactions by mean and propo...         Actual   
20357  Electronic card transactions by mean and propo...         Actual   
20358  Electronic card transactions by mean and propo...         Actual   
20359  Electronic card transactions by mean and propo...         Actual   
20360  Electronic card transactions by mean and propo...         Actual   

                                          Series_title_2  Series_title_3  \
0                                   RTS total industries             NaN   
1                                   RTS total industries             NaN   
2                                   RTS total industries             NaN   
3                                   RTS total industries             NaN   
4                                   RTS total industries             NaN   
...                                                  ...             ...   
20356  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20357  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20358  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20359  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20360  Debit card usage as a proportion of total ECT ...  Proportion (%)   

       Series_title_4  Series_title_5  
0                 NaN             NaN  
1                 NaN             NaN  
2                 NaN             NaN  
3                 NaN             NaN  
4                 NaN             NaN  
...               ...             ...  
20356             NaN             NaN  
20357             NaN             NaN  
20358             NaN             NaN  
20359             NaN             NaN  
20360             NaN             NaN  

[20361 rows x 14 

# statistic functions

In [154]:
import numpy as np

In [155]:
x= np.array([[1,2,3],[2,4,6],[90,100,50]])

In [156]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [157]:
np.amin(x)

1

In [158]:
np.amax(x)

100

In [159]:
np.amin(x, axis=1)

array([ 1,  2, 50])

In [160]:
np.amin(x,axis=0)

array([1, 2, 3])

In [161]:
np.amax(x,axis=0)

array([ 90, 100,  50])

In [162]:
np.amax(x,axis=1)

array([  3,   6, 100])

In [163]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [164]:
np.average(x)

28.666666666666668

# weighted average

In [165]:
w=[1,2,3]

In [167]:
np.average(x, weights=w,axis=0)

array([45.83333333, 51.66666667, 27.5       ])

In [168]:
np.average(x,weights=w,axis=1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [169]:
np.mean(x)

28.666666666666668

In [170]:
np.mean(x[1])

4.0

In [171]:
np.mean(x[2])

80.0

In [172]:
np.mean(x, axis=0)

array([31.        , 35.33333333, 19.66666667])

In [173]:
np.mean(x, axis=1)

array([ 2.,  4., 80.])

In [174]:
np.median(x)

4.0

In [175]:
np.median(x,axis=1)

array([ 2.,  4., 90.])

In [176]:
np.median(x,axis=0)

array([2., 4., 6.])

In [177]:
np.var(x)

1474.888888888889

In [178]:
np.std(x)

38.4042821686448